---
sudo: required
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install -r requirements.txt
script:
  - molecule test